### ISSUE TITLE
Adicionar documentação do EducAPIManager

### ISSUE THREAD

**Issue by ayladebora** [a4s-ufpb/EducAPI-Manager#2]
# Relatório de Bug

### Pré Requisitos
> Acessar o git do projeto
 
### Passos 
> Entrar no git do projeto.

### Resultado esperado
> Que a documentação inicial aponte o passo a passo para colocar o projeto para funcionar.

### Evidencias 
> A documentação não existe hoje em dia.

### Possível Solução 
> Atualizar a documentação.

##### Ambiente: 
* [X ]  Produção
* [ ]  Desenvolvimento
* [ ]  Outro
> Se selecionou 'Outro', especifique.

##### Versão: 
> 0.1

##### Outros artefatos:
>

**Comment by EduardoGhost** [comment]
> # Relatório de Bug
> ### Pré Requisitos
> > Acessar o git do projeto
> 
> ### Passos
> > Entrar no git do projeto.
> 
> ### Resultado esperado
> > Que a documentação inicial aponte o passo a passo para colocar o projeto para funcionar.
> 
> ### Evidencias
> > A documentação não existe hoje em dia.
> 
> ### Possível Solução
> > Atualizar a documentação.
> 
> ### Artefatos
> ##### Ambiente:
> * [X ]  Produção
> * [ ]   Desenvolvimento
> * [ ]   Outro
> 
> > Se selecionou 'Outro', especifique.
> 
> ##### Versão:
> > 0.1
> 
> ##### Outros artefatos:
> >
